
from websocket import create_connection
ws = create_connection("ws://localhost:8001/")
ws.settimeout(15.0)


print("Sending 'Hello, World'...")
ws.send("Hello, World")
print("Sent")
print("Receiving...")
result = ws.recv()
print("Received '%s'" % result)

print("Sending 'Hello, World'...")
ws.send("Hello, World23")
print("Sent")
print("Receiving...")
result = ws.recv()
print("Received '%s'" % result)
print("Sending 'Hello, World'...")
ws.send("Hello, World3")
print("Sent")
print("Receiving...")
result = ws.recv()
print("Received '%s'" % result)
print("Sending 'Hello, World'...")
ws.send("Hello, World4")
print("Sent")
print("Receiving...")
result = ws.recv()
print("Received '%s'" % result)
print("Sending 'Hello, World'...")
ws.send("Hello, World")
print("Sent")
print("Receiving...")
result = ws.recv()
print("Received '%s'" % result)
ws.close()

